(function () {
  'use strict';
  const devHost = host => host === 'localhost' || host === '127.0.0.1' || host === 'dev.suyogjoshi.com' || host === 'feature-epic-586-course-inte.suyogjoshi-dev.pages.dev';
  const prodHost = host => ['suyogjoshi.com', 'www.suyogjoshi.com'].includes(host);
  const base = devHost(location.hostname) ? 'https://api-dev.suyogjoshi.com' : prodHost(location.hostname) ? 'https://api.suyogjoshi.com' : '';
  function validItem(item) { const text = value => typeof value === 'string' && value.trim().length > 0; if (!item || !text(item.courseId) || !text(item.publicTitle) || !text(item.slug) || !Number.isInteger(item.stage) || item.stage < 1 || item.stage > 5 || typeof item.interestCaptureEnabled !== 'boolean') return false; const topics = () => Array.isArray(item.topicOptions) && item.topicOptions.length <= 20 && item.topicOptions.every(text); const consent = () => item.interestCaptureEnabled === true && text(item.consentStatement) && text(item.consentVersion); if (item.primaryAction === 'APPLY') return item.publicStatus === 'APPLICATIONS_OPEN' && item.topicOptions === undefined && item.consentStatement === undefined && item.consentVersion === undefined; if (item.primaryAction === 'GET_NOTIFIED') return item.publicStatus === 'APPLICATIONS_NOT_OPEN' && consent() && topics() && item.topicOptions.length === 0; if (item.primaryAction === 'REGISTER_INTEREST') return item.publicStatus === 'COMING_LATER' && consent() && topics(); if (item.primaryAction === 'NONE') return item.interestCaptureEnabled === false && ['APPLICATIONS_NOT_OPEN', 'COMING_LATER'].includes(item.publicStatus) && item.topicOptions === undefined && item.consentStatement === undefined && item.consentVersion === undefined; return false; }
  function interestUrl(item, source, locationName) { return `/training/register-interest/?courseId=${encodeURIComponent(item.courseId)}&sourceSurface=${source}&ctaLocation=${locationName}`; }
  function updateLink(link, item, source, locationName) { if (item.primaryAction === 'APPLY') { link.href = `/apply/?courseId=${encodeURIComponent(item.courseId)}`; link.textContent = 'Apply'; link.hidden = false; } else if (item.primaryAction === 'GET_NOTIFIED') { link.href = interestUrl(item, source, locationName); link.textContent = 'Get notified'; link.hidden = false; } else if (item.primaryAction === 'REGISTER_INTEREST') { link.href = interestUrl(item, source, locationName); link.textContent = 'Register interest'; link.hidden = false; } else { link.hidden = true; link.removeAttribute('href'); } }
  function detailActionLinks() { return document.querySelectorAll('.course-hero [data-cta-location], .course-detail-hero [data-cta-location], [data-enrolment-card] [data-cta-location], [data-final-cta] [data-cta-location], [data-mobile-course-cta] a'); }
  function failClosed() { document.querySelectorAll('[data-course-action="notify"], [data-course-action="interest"]').forEach(link => { link.hidden = true; link.removeAttribute('href'); }); detailActionLinks().forEach(link => { link.hidden = true; link.removeAttribute('href'); }); }
  async function initialise() {
    if (!base) { failClosed(); return; }
    try {
      const response = await fetch(`${base}/training/course-actions`, { headers: { Accept: 'application/json' }, cache: 'no-store' }); if (!response.ok) throw new Error('actions'); const body = await response.json(); if (!Array.isArray(body.items) || body.items.some(item => !validItem(item))) throw new Error('invalid actions'); const byId = new Map(body.items.map(item => [item.courseId, item]));
      const page = document.querySelector('[data-course-detail]'); if (page) { const item = byId.get(page.dataset.courseId); if (!item) { failClosed(); return; } detailActionLinks().forEach(link => updateLink(link, item, 'COURSE_PAGE', (link.dataset.ctaLocation || (link.closest('[data-mobile-course-cta]') ? 'MOBILE' : 'ENROLMENT_PANEL')).toUpperCase())); }
    } catch (_) { failClosed(); }
  }
  window.sjCourseActions = { initialise, interestUrl, validItem }; window.sjCourseActionsReady = initialise();
}());
